<?php

declare(strict_types=1);

namespace MageOS\Seo\Model\Hreflang;

use Magento\Framework\App\ResourceConnection;

/**
 * Reads canonical URL rewrites from the url_rewrite table for hreflang resolution.
 *
 * Only autogenerated, non-redirect rows are used, so each store maps to its current canonical
 * request path. Stores where an entity has no rewrite (e.g. not assigned to that store) are simply
 * absent — which is exactly the correct hreflang behaviour.
 */
class UrlRewriteFetcher
{
    /**
     * @param ResourceConnection $resourceConnection
     */
    public function __construct(
        private readonly ResourceConnection $resourceConnection
    ) {
    }

    /**
     * Fetch canonical request paths for one entity, keyed by store ID.
     *
     * @param string $entityType 'product' | 'category' | 'cms-page'
     * @param int $entityId
     * @return array<int, string> store_id => request_path
     */
    public function fetchForEntity(string $entityType, int $entityId): array
    {
        $connection = $this->resourceConnection->getConnection();
        $table      = $connection->getTableName('url_rewrite');

        $rows = $connection->fetchAll(
            $connection->select()
                ->from($table, ['store_id', 'request_path'])
                ->where('entity_type = ?', $entityType)
                ->where('entity_id = ?', $entityId)
                ->where('redirect_type = ?', 0)
                ->where('is_autogenerated = ?', 1)
        );

        $paths = [];
        foreach ($rows as $row) {
            $storeId = (int) $row['store_id'];
            // First canonical row per store wins; later history rows are ignored.
            if (!isset($paths[$storeId])) {
                $paths[$storeId] = (string) $row['request_path'];
            }
        }

        return $paths;
    }

    /**
     * Bulk-fetch canonical request paths for every entity of a type, for the sitemap generator.
     *
     * One query for the whole catalogue. Returns entity_id => [store_id => request_path].
     *
     * @param string $entityType
     * @param int[] $storeIds
     * @return array<int, array<int, string>>
     */
    public function fetchAllForType(string $entityType, array $storeIds): array
    {
        if ($storeIds === []) {
            return [];
        }

        $connection = $this->resourceConnection->getConnection();
        $table      = $connection->getTableName('url_rewrite');

        $rows = $connection->fetchAll(
            $connection->select()
                ->from($table, ['entity_id', 'store_id', 'request_path'])
                ->where('entity_type = ?', $entityType)
                ->where('store_id IN (?)', $storeIds)
                ->where('redirect_type = ?', 0)
                ->where('is_autogenerated = ?', 1)
        );

        $result = [];
        foreach ($rows as $row) {
            $entityId = (int) $row['entity_id'];
            $storeId  = (int) $row['store_id'];
            if (!isset($result[$entityId][$storeId])) {
                $result[$entityId][$storeId] = (string) $row['request_path'];
            }
        }

        return $result;
    }
}
