<?php

declare(strict_types=1);

namespace MageOS\Seo\Controller\Hreflangsitemap;

use Magento\Framework\App\Action\HttpGetActionInterface;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\Controller\Result\RawFactory;
use Magento\Framework\Controller\ResultInterface;
use Magento\Store\Model\StoreManagerInterface;
use MageOS\Seo\Model\Config;
use MageOS\Seo\Model\Feed\CanonicalPathRedirect;
use MageOS\Seo\Model\Feed\FeedRegenerator;
use MageOS\Seo\Model\Feed\FeedStorage;
use MageOS\Seo\Model\Feed\RegenerationRequester;
use MageOS\Seo\Model\Hreflang\SitemapGenerator;
use MageOS\Seo\Model\Hreflang\StoreLocaleMap;

/**
 * Serves /hreflang-sitemap.xml and its numbered chunk files.
 *
 * Small catalogues get a single urlset at /hreflang-sitemap.xml; larger ones get a
 * sitemap index there referencing /hreflang-sitemap-N.xml chunks (50k-URL protocol
 * cap). Files are pre-generated by cron and the regeneration queue consumer; web
 * requests never build them — a missing base file queues a rebuild and answers
 * 503 Retry-After.
 *
 * Returns 404 when hreflang or the sitemap is disabled, when fewer than two store
 * views are eligible, or for a chunk that does not exist in the current file set.
 */
class Index implements HttpGetActionInterface
{
    /**
     * @param StoreLocaleMap $storeLocaleMap
     * @param RawFactory $rawFactory
     * @param Config $seoConfig
     * @param FeedStorage $feedStorage
     * @param CanonicalPathRedirect $canonicalPathRedirect
     * @param RegenerationRequester $regenerationRequester
     * @param StoreManagerInterface $storeManager
     * @param RequestInterface $request
     */
    public function __construct(
        private readonly StoreLocaleMap        $storeLocaleMap,
        private readonly RawFactory            $rawFactory,
        private readonly Config                $seoConfig,
        private readonly FeedStorage           $feedStorage,
        private readonly CanonicalPathRedirect $canonicalPathRedirect,
        private readonly RegenerationRequester $regenerationRequester,
        private readonly StoreManagerInterface $storeManager,
        private readonly RequestInterface      $request,
    ) {
    }

    /**
     * Serve the requested hreflang sitemap file with cache headers.
     *
     * @return ResultInterface
     */
    public function execute(): ResultInterface
    {
        $chunk    = max(0, (int) $this->request->getParam('chunk', 0));
        $fileName = $chunk > 0
            ? \sprintf(SitemapGenerator::CHUNK_FORMAT, $chunk)
            : SitemapGenerator::INDEX_FILE;

        $redirect = $this->canonicalPathRedirect->check($fileName);
        if ($redirect !== null) {
            return $redirect;
        }

        $result = $this->rawFactory->create();

        $disabled = !$this->seoConfig->isHreflangEnabled() || !$this->seoConfig->isHreflangSitemapEnabled();
        if ($disabled || \count($this->storeLocaleMap->getMap()) < 2) {
            $result->setHttpResponseCode(404);
            $result->setContents('');
            return $result;
        }

        $storeId = (int) $this->storeManager->getStore()->getId();
        $content = $this->feedStorage->read($fileName, $storeId);

        if ($content === null) {
            $baseExists = $chunk > 0
                && $this->feedStorage->read(SitemapGenerator::INDEX_FILE, $storeId) !== null;
            if ($baseExists) {
                // The file set is current and this chunk simply doesn't exist.
                $result->setHttpResponseCode(404);
                $result->setContents('');
                return $result;
            }

            $this->regenerationRequester->request(FeedRegenerator::GROUP_HREFLANG);
            $result->setHttpResponseCode(503);
            $result->setHeader('Retry-After', '120', true);
            $result->setContents('');
            return $result;
        }

        $result->setHttpResponseCode(200);
        $result->setHeader('Content-Type', 'application/xml; charset=utf-8', true);
        $result->setHeader('Cache-Control', 'public, max-age=86400, s-maxage=86400', true);
        $result->setHeader('X-Magento-Tags', 'MAGEOS_SEO_HREFLANG_SITEMAP', true);
        $result->setContents($content);

        return $result;
    }
}
